POST http://localhost:3000/utilizadores/registar
Content-Type: application/json

{
    "nome": "Vânia Correia",
    "email": "admin@admin.com",
    "password": "admin37",
    "nif": "123456789",
    "contacto": "917777777",
    "tipo": "Administrador"
}

###

POST http://localhost:3000/utilizadores/registar
Content-Type: application/json

{
    "nome": "Utilizador1",
    "email": "user@user.com",
    "password": "admin37",
    "nif": "123456788",
    "contacto": "918888888"
}

###

POST http://localhost:3000/utilizadores/registar
Content-Type: application/json

{
    "nome": "Utilizador2",
    "email": "user22@user.com",
    "password": "admin37",
    "nif": "123456998",
    "contacto": "918888899",
     "tipo": "Administrador"
}

###

POST http://localhost:3000/utilizadores/autenticacao
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin37"
}

###

POST http://localhost:3000/utilizadores/autenticacao
Content-Type: application/json

{
    "email": "user@user.com",
    "password": "admin37"
}

###
POST http://localhost:3000/utilizadores/autenticacao
Content-Type: application/json

{
    "email": "user22@user.com",
    "password": "admin37"
}

###
POST http://localhost:3000/utilizadores/registar
Content-Type: application/json

{
    "nome": "Utilizador2",
    "email": "admin22@user.com",
    "password": "admin37",
    "nif": "133456998",
    "contacto": "918888899",
    "tipo": "administrador"
}


###
POST http://localhost:3000/utilizadores/autenticacao
Content-Type: application/json

{
    "email": "admin22@user.com",
    "password": "admin37"
}